spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3307/nopainnogain?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3308/nopainnogain?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: readOnlyUser
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #com.mysql.jdbc.Driver 废弃

# Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
#池中维护的最小空闲连接数
    hikari:
      minimum-idle: 5
#池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 15
#自动提交从池中返回的连接
      auto-commit: true
#连接允许在池中闲置的最长时间
      idle-timeout: 30000
#连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      pool-name: DatebookHikariCP
#池中连接最长生命周期
      max-lifetime: 1800000
#等待来自池的连接的最大毫秒数
      connection-timeout: 30000
      connection-test-query: SELECT 1