spring:
  profiles:
    active: prod
# ActiveMQ
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
#  jms:
#    pub-sub-domain: false  # 启用发布订阅模式（默认关闭是点对点模式）

server:
  port: 8082